version: "3.9"
services:
  kvira_bot_app:
    container_name: kvira_bot_app
    # restart: always
    build: .
    # depends_on:
    #   - kvira_redis
    networks:
      - bot_network
    # .env file
    env_file:
      - .env
    # Create volume from file with env variable called GOOGLE_KEY_FILE_PATH
    volumes:
      - ./${GOOGLE_KEY_FILE_PATH}:/${GOOGLE_KEY_FILE_PATH}

  kvira_redis:
    container_name: kvira_redis
    image: redis
    restart: always
    # Persistent storage
    volumes:
      - ./redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    environment:
    - REDIS_MAXMEMORY=1024mb # Limit Redis memory usage to 1024mb
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge